version: "2.4"
services:
  mongo:
    image: mongo:4.0.4
    ports:
      - "27017:27017"
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.1
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node
  dev:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - elastic
      - mongo
    links:
      - mongo
      - elastic
    command: ["./wait-for-it.sh", "elastic:9200", "--", "npm", "start"]

